[project]
name = "cryptomock_server"
version = "0.1.0"
description = "CryptoMock is experiment to mock main cryptolocker's call"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "cryptography>=45.0.6",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
